// countryData.js

export const countries = [
  // === EUROPEAN UNION (27 Countries - GDPR Applies) ===
  { name: "Austria", timezone: "Europe/Vienna", isEU: true },
  { name: "Belgium", timezone: "Europe/Brussels", isEU: true },
  { name: "Bulgaria", timezone: "Europe/Sofia", isEU: true },
  { name: "Croatia", timezone: "Europe/Zagreb", isEU: true },
  { name: "Cyprus", timezone: "Asia/Nicosia", isEU: true },
  { name: "Czech Republic", timezone: "Europe/Prague", isEU: true },
  { name: "Denmark", timezone: "Europe/Copenhagen", isEU: true },
  { name: "Estonia", timezone: "Europe/Tallinn", isEU: true },
  { name: "Finland", timezone: "Europe/Helsinki", isEU: true },
  { name: "France", timezone: "Europe/Paris", isEU: true },
  { name: "Germany", timezone: "Europe/Berlin", isEU: true },
  { name: "Greece", timezone: "Europe/Athens", isEU: true },
  { name: "Hungary", timezone: "Europe/Budapest", isEU: true },
  { name: "Ireland", timezone: "Europe/Dublin", isEU: true },
  { name: "Italy", timezone: "Europe/Rome", isEU: true },
  { name: "Latvia", timezone: "Europe/Riga", isEU: true },
  { name: "Lithuania", timezone: "Europe/Vilnius", isEU: true },
  { name: "Luxembourg", timezone: "Europe/Luxembourg", isEU: true },
  { name: "Malta", timezone: "Europe/Malta", isEU: true },
  { name: "Netherlands", timezone: "Europe/Amsterdam", isEU: true },
  { name: "Poland", timezone: "Europe/Warsaw", isEU: true },
  { name: "Portugal", timezone: "Europe/Lisbon", isEU: true },
  { name: "Romania", timezone: "Europe/Bucharest", isEU: true },
  { name: "Slovakia", timezone: "Europe/Bratislava", isEU: true },
  { name: "Slovenia", timezone: "Europe/Ljubljana", isEU: true },
  { name: "Spain", timezone: "Europe/Madrid", isEU: true },
  { name: "Sweden", timezone: "Europe/Stockholm", isEU: true },

  // === ALL OTHER WORLD COUNTRIES (Non-EU) ===
  { name: "Afghanistan", timezone: "Asia/Kabul", isEU: false },
  { name: "Albania", timezone: "Europe/Tirane", isEU: false },
  { name: "Algeria", timezone: "Africa/Algiers", isEU: false },
  { name: "Andorra", timezone: "Europe/Andorra", isEU: false },
  { name: "Angola", timezone: "Africa/Luanda", isEU: false },
  { name: "Antigua and Barbuda", timezone: "America/Antigua", isEU: false },
  { name: "Argentina", timezone: "America/Argentina/Buenos_Aires", isEU: false },
  { name: "Armenia", timezone: "Asia/Yerevan", isEU: false },
  { name: "Australia", timezone: "Australia/Sydney", isEU: false },
  { name: "Azerbaijan", timezone: "Asia/Baku", isEU: false },
  { name: "Bahamas", timezone: "America/Nassau", isEU: false },
  { name: "Bahrain", timezone: "Asia/Bahrain", isEU: false },
  { name: "Bangladesh", timezone: "Asia/Dhaka", isEU: false },
  { name: "Barbados", timezone: "America/Barbados", isEU: false },
  { name: "Belarus", timezone: "Europe/Minsk", isEU: false },
  { name: "Belize", timezone: "America/Belize", isEU: false },
  { name: "Benin", timezone: "Africa/Porto-Novo", isEU: false },
  { name: "Bhutan", timezone: "Asia/Thimphu", isEU: false },
  { name: "Bolivia", timezone: "America/La_Paz", isEU: false },
  { name: "Bosnia and Herzegovina", timezone: "Europe/Sarajevo", isEU: false },
  { name: "Botswana", timezone: "Africa/Gaborone", isEU: false },
  { name: "Brazil", timezone: "America/Sao_Paulo", isEU: false },
  { name: "Brunei", timezone: "Asia/Brunei", isEU: false },
  { name: "Burkina Faso", timezone: "Africa/Ouagadougou", isEU: false },
  { name: "Burundi", timezone: "Africa/Bujumbura", isEU: false },
  { name: "Cabo Verde", timezone: "Atlantic/Cape_Verde", isEU: false },
  { name: "Cambodia", timezone: "Asia/Phnom_Penh", isEU: false },
  { name: "Cameroon", timezone: "Africa/Douala", isEU: false },
  { name: "Canada", timezone: "America/Toronto", isEU: false },
  { name: "Central African Republic", timezone: "Africa/Bangui", isEU: false },
  { name: "Chad", timezone: "Africa/Ndjamena", isEU: false },
  { name: "Chile", timezone: "America/Santiago", isEU: false },
  { name: "China", timezone: "Asia/Shanghai", isEU: false },
  { name: "Colombia", timezone: "America/Bogota", isEU: false },
  { name: "Comoros", timezone: "Indian/Comoro", isEU: false },
  { name: "Congo (Congo-Brazzaville)", timezone: "Africa/Brazzaville", isEU: false },
  { name: "Costa Rica", timezone: "America/Costa_Rica", isEU: false },
  { name: "Cuba", timezone: "America/Havana", isEU: false },
  { name: "Democratic Republic of the Congo", timezone: "Africa/Kinshasa", isEU: false },
  { name: "Djibouti", timezone: "Africa/Djibouti", isEU: false },
  { name: "Dominica", timezone: "America/Dominica", isEU: false },
  { name: "Dominican Republic", timezone: "America/Santo_Domingo", isEU: false },
  { name: "Ecuador", timezone: "America/Guayaquil", isEU: false },
  { name: "Egypt", timezone: "Africa/Cairo", isEU: false },
  { name: "El Salvador", timezone: "America/El_Salvador", isEU: false },
  { name: "Equatorial Guinea", timezone: "Africa/Malabo", isEU: false },
  { name: "Eritrea", timezone: "Africa/Asmara", isEU: false },
  { name: "Eswatini", timezone: "Africa/Mbabane", isEU: false },
  { name: "Ethiopia", timezone: "Africa/Addis_Ababa", isEU: false },
  { name: "Fiji", timezone: "Pacific/Fiji", isEU: false },
  { name: "Gabon", timezone: "Africa/Libreville", isEU: false },
  { name: "Gambia", timezone: "Africa/Banjul", isEU: false },
  { name: "Georgia", timezone: "Asia/Tbilisi", isEU: false },
  { name: "Ghana", timezone: "Africa/Accra", isEU: false },
  { name: "Grenada", timezone: "America/Grenada", isEU: false },
  { name: "Guatemala", timezone: "America/Guatemala", isEU: false },
  { name: "Guinea", timezone: "Africa/Conakry", isEU: false },
  { name: "Guinea-Bissau", timezone: "Africa/Bissau", isEU: false },
  { name: "Guyana", timezone: "America/Guyana", isEU: false },
  { name: "Haiti", timezone: "America/Port-au-Prince", isEU: false },
  { name: "Honduras", timezone: "America/Tegucigalpa", isEU: false },
  { name: "Iceland", timezone: "Atlantic/Reykjavik", isEU: false },
  { name: "India", timezone: "Asia/Kolkata", isEU: false },
  { name: "Indonesia", timezone: "Asia/Jakarta", isEU: false },
  { name: "Iran", timezone: "Asia/Tehran", isEU: false },
  { name: "Iraq", timezone: "Asia/Baghdad", isEU: false },
  { name: "Israel", timezone: "Asia/Jerusalem", isEU: false },
  { name: "Jamaica", timezone: "America/Jamaica", isEU: false },
  { name: "Japan", timezone: "Asia/Tokyo", isEU: false },
  { name: "Jordan", timezone: "Asia/Amman", isEU: false },
  { name: "Kazakhstan", timezone: "Asia/Almaty", isEU: false },
  { name: "Kenya", timezone: "Africa/Nairobi", isEU: false },
  { name: "Kiribati", timezone: "Pacific/Tarawa", isEU: false },
  { name: "Kuwait", timezone: "Asia/Kuwait", isEU: false },
  { name: "Kyrgyzstan", timezone: "Asia/Bishkek", isEU: false },
  { name: "Laos", timezone: "Asia/Vientiane", isEU: false },
  { name: "Lebanon", timezone: "Asia/Beirut", isEU: false },
  { name: "Lesotho", timezone: "Africa/Maseru", isEU: false },
  { name: "Liberia", timezone: "Africa/Monrovia", isEU: false },
  { name: "Libya", timezone: "Africa/Tripoli", isEU: false },
  { name: "Liechtenstein", timezone: "Europe/Vaduz", isEU: false },
  { name: "Madagascar", timezone: "Indian/Antananarivo", isEU: false },
  { name: "Malawi", timezone: "Africa/Blantyre", isEU: false },
  { name: "Malaysia", timezone: "Asia/Kuala_Lumpur", isEU: false },
  { name: "Maldives", timezone: "Indian/Maldives", isEU: false },
  { name: "Mali", timezone: "Africa/Bamako", isEU: false },
  { name: "Marshall Islands", timezone: "Pacific/Majuro", isEU: false },
  { name: "Mauritania", timezone: "Africa/Nouakchott", isEU: false },
  { name: "Mauritius", timezone: "Indian/Mauritius", isEU: false },
  { name: "Mexico", timezone: "America/Mexico_City", isEU: false },
  { name: "Micronesia", timezone: "Pacific/Chuuk", isEU: false },
  { name: "Moldova", timezone: "Europe/Chisinau", isEU: false },
  { name: "Monaco", timezone: "Europe/Monaco", isEU: false },
  { name: "Mongolia", timezone: "Asia/Ulaanbaatar", isEU: false },
  { name: "Montenegro", timezone: "Europe/Podgorica", isEU: false },
  { name: "Morocco", timezone: "Africa/Casablanca", isEU: false },
  { name: "Mozambique", timezone: "Africa/Maputo", isEU: false },
  { name: "Myanmar (Burma)", timezone: "Asia/Yangon", isEU: false },
  { name: "Namibia", timezone: "Africa/Windhoek", isEU: false },
  { name: "Nauru", timezone: "Pacific/Nauru", isEU: false },
  { name: "Nepal", timezone: "Asia/Kathmandu", isEU: false },
  { name: "New Zealand", timezone: "Pacific/Auckland", isEU: false },
  { name: "Nicaragua", timezone: "America/Managua", isEU: false },
  { name: "Niger", timezone: "Africa/Niamey", isEU: false },
  { name: "Nigeria", timezone: "Africa/Lagos", isEU: false },
  { name: "North Korea", timezone: "Asia/Pyongyang", isEU: false },
  { name: "North Macedonia", timezone: "Europe/Skopje", isEU: false },
  { name: "Norway", timezone: "Europe/Oslo", isEU: false },
  { name: "Oman", timezone: "Asia/Muscat", isEU: false },
  { name: "Pakistan", timezone: "Asia/Karachi", isEU: false },
  { name: "Palau", timezone: "Pacific/Palau", isEU: false },
  { name: "Panama", timezone: "America/Panama", isEU: false },
  { name: "Papua New Guinea", timezone: "Pacific/Port_Moresby", isEU: false },
  { name: "Paraguay", timezone: "America/Asuncion", isEU: false },
  { name: "Peru", timezone: "America/Lima", isEU: false },
  { name: "Philippines", timezone: "Asia/Manila", isEU: false },
  { name: "Qatar", timezone: "Asia/Qatar", isEU: false },
  { name: "Russia", timezone: "Europe/Moscow", isEU: false },
  { name: "Rwanda", timezone: "Africa/Kigali", isEU: false },
  { name: "Saint Kitts and Nevis", timezone: "America/St_Kitts", isEU: false },
  { name: "Saint Lucia", timezone: "America/St_Lucia", isEU: false },
  { name: "Saint Vincent and the Grenadines", timezone: "America/St_Vincent", isEU: false },
  { name: "Samoa", timezone: "Pacific/Apia", isEU: false },
  { name: "San Marino", timezone: "Europe/San_Marino", isEU: false },
  { name: "Sao Tome and Principe", timezone: "Africa/Sao_Tome", isEU: false },
  { name: "Saudi Arabia", timezone: "Asia/Riyadh", isEU: false },
  { name: "Senegal", timezone: "Africa/Dakar", isEU: false },
  { name: "Serbia", timezone: "Europe/Belgrade", isEU: false },
  { name: "Seychelles", timezone: "Indian/Mahe", isEU: false },
  { name: "Sierra Leone", timezone: "Africa/Freetown", isEU: false },
  { name: "Singapore", timezone: "Asia/Singapore", isEU: false },
  { name: "Solomon Islands", timezone: "Pacific/Guadalcanal", isEU: false },
  { name: "Somalia", timezone: "Africa/Mogadishu", isEU: false },
  { name: "South Africa", timezone: "Africa/Johannesburg", isEU: false },
  { name: "South Korea", timezone: "Asia/Seoul", isEU: false },
  { name: "South Sudan", timezone: "Africa/Juba", isEU: false },
  { name: "Sri Lanka", timezone: "Asia/Colombo", isEU: false },
  { name: "Sudan", timezone: "Africa/Khartoum", isEU: false },
  { name: "Suriname", timezone: "America/Paramaribo", isEU: false },
  { name: "Switzerland", timezone: "Europe/Zurich", isEU: false },
  { name: "Syria", timezone: "Asia/Damascus", isEU: false },
  { name: "Tajikistan", timezone: "Asia/Dushanbe", isEU: false },
  { name: "Tanzania", timezone: "Africa/Dar_es_Salaam", isEU: false },
  { name: "Thailand", timezone: "Asia/Bangkok", isEU: false },
  { name: "Togo", timezone: "Africa/Lome", isEU: false },
  { name: "Tonga", timezone: "Pacific/Tongatapu", isEU: false },
  { name: "Trinidad and Tobago", timezone: "America/Port_of_Spain", isEU: false },
  { name: "Tunisia", timezone: "Africa/Tunis", isEU: false },
  { name: "Turkey", timezone: "Europe/Istanbul", isEU: false },
  { name: "Turkmenistan", timezone: "Asia/Ashgabat", isEU: false },
  { name: "Tuvalu", timezone: "Pacific/Funafuti", isEU: false },
  { name: "Uganda", timezone: "Africa/Kampala", isEU: false },
  { name: "Ukraine", timezone: "Europe/Kiev", isEU: false },
  { name: "United Arab Emirates", timezone: "Asia/Dubai", isEU: false },
  { name: "United Kingdom", timezone: "Europe/London", isEU: false },
  { name: "United States (Eastern)", timezone: "America/New_York", isEU: false },
  { name: "United States (Central)", timezone: "America/Chicago", isEU: false },
  { name: "United States (Mountain)", timezone: "America/Denver", isEU: false },
  { name: "United States (Pacific)", timezone: "America/Los_Angeles", isEU: false },
  { name: "Uruguay", timezone: "America/Montevideo", isEU: false },
  { name: "Uzbekistan", timezone: "Asia/Tashkent", isEU: false },
  { name: "Vanuatu", timezone: "Pacific/Efate", isEU: false },
  { name: "Vatican City", timezone: "Europe/Vatican", isEU: false },
  { name: "Venezuela", timezone: "America/Caracas", isEU: false },
  { name: "Vietnam", timezone: "Asia/Ho_Chi_Minh", isEU: false },
  { name: "Yemen", timezone: "Asia/Aden", isEU: false },
  { name: "Zambia", timezone: "Africa/Lusaka", isEU: false },
  { name: "Zimbabwe", timezone: "Africa/Harare", isEU: false }
];
